# Generated by Django 6.0.5 on 2026-05-26 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('github_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('content', models.TextField()),
                ('cover_image', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('read_time', models.PositiveIntegerField(default=3)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, default='', max_length=300)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.publication')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
