# Generated by Django 6.0.5 on 2026-06-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_seed_auto_cars_tiago_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='github_url',
        ),
    ]
