# Generated by Django 6.0.5 on 2026-06-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_user_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinghistory',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='blog.article'),
        ),
    ]
