"""
Django settings for writeflow project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

import os

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-in-production')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1')

# Build ALLOWED_HOSTS: explicit env var + auto-detect Vercel domain
_allowed = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
_vercel_url = os.environ.get('VERCEL_URL', '')          # e.g. us-content-hub.vercel.app
_vercel_branch_url = os.environ.get('VERCEL_BRANCH_URL', '')
for _vh in [_vercel_url, _vercel_branch_url]:
    if _vh and _vh not in _allowed:
        _allowed.append(_vh)
ALLOWED_HOSTS = _allowed

# Build CSRF origins: explicit env var + auto-detect Vercel URL
_csrf = [o.strip() for o in os.environ.get('DJANGO_CSRF_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',') if o.strip()]
if _vercel_url and f'https://{_vercel_url}' not in _csrf:
    _csrf.append(f'https://{_vercel_url}')
CSRF_TRUSTED_ORIGINS = _csrf

# ── Guard: fail loudly if insecure default key is used in production ──
if not DEBUG and SECRET_KEY == 'django-insecure-dev-only-change-in-production':
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable must be set to a strong random "
        "value in production. Never use the insecure development default."
    )

# Site URL — used in robots.txt, sitemaps, and email links
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000').rstrip('/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'blog',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves static files in production
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'writeflow.urls'

_TEMPLATE_LOADERS = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'blog' / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            # In production, wrap loaders in cached.Loader so templates are
            # parsed once and reused — eliminates repeated disk I/O per request.
            'loaders': (
                _TEMPLATE_LOADERS
                if DEBUG
                else [('django.template.loaders.cached.Loader', _TEMPLATE_LOADERS)]
            ),
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.publications',
            ],
        },
    },
]

WSGI_APPLICATION = 'writeflow.wsgi.application'


# ============================================================
# DATABASE — PostgreSQL in production, SQLite in development
# Set DATABASE_URL env var to switch:
#   postgres://user:pass@host:5432/dbname   → PostgreSQL
#   mysql://user:pass@host:3306/dbname      → MySQL (PythonAnywhere free tier)
#   (not set)                               → SQLite (local dev / tests)
# ============================================================
_DATABASE_URL = os.environ.get('DATABASE_URL', '')

if _DATABASE_URL.startswith('postgres'):
    import urllib.parse as _urlparse
    _parsed = _urlparse.urlparse(_DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _parsed.path.lstrip('/'),
            'USER': _parsed.username or '',
            'PASSWORD': _parsed.password or '',
            'HOST': _parsed.hostname or 'localhost',
            'PORT': _parsed.port or 5432,
            'CONN_MAX_AGE': 600,           # keep connections alive for 10 min
            'OPTIONS': {'sslmode': 'prefer'},
        }
    }
elif _DATABASE_URL.startswith('mysql'):
    import urllib.parse as _urlparse
    _parsed = _urlparse.urlparse(_DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': _parsed.path.lstrip('/'),
            'USER': _parsed.username or '',
            'PASSWORD': _parsed.password or '',
            'HOST': _parsed.hostname or 'localhost',
            'PORT': _parsed.port or 3306,
            'CONN_MAX_AGE': 600,
        }
    }
else:
    # Development / test fallback — SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# CompressedManifestStaticFilesStorage appends a content hash to filenames,
# so files can be cached indefinitely — browsers fetch a new URL on any change.
WHITENOISE_MAX_AGE = 31536000  # 1 year

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/accounts/logout/'

# ============================================================
# CACHING — Redis in production (set REDIS_URL), LocMemCache for dev/tests
# Example: REDIS_URL=redis://localhost:6379/0
# Note: LocMemCache is process-local; on multi-worker deployments each
# worker has its own cache. Switch to Redis for consistency.
# ============================================================
_REDIS_URL = os.environ.get('REDIS_URL', '')

if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            },
        }
    }
else:
    # Development / test fallback — in-process memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'uch-cache-v1',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            },
        }
    }

# ============================================================
# SESSIONS — signed cookies work on Vercel serverless without
# any external storage. Use cache-backed sessions when Redis
# is available (multi-worker / stateful deployments).
# ============================================================
if _REDIS_URL:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
else:
    # signed_cookies: session data lives in the browser cookie,
    # signed + encrypted with SECRET_KEY — no server-side storage needed.
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# ============================================================
# SECURITY SETTINGS — enforced in production
# ============================================================
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = bool(os.environ.get('DJANGO_SECURE_SSL', ''))
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ============================================================
# ALLAUTH — Social Authentication (Google, Microsoft)
# ============================================================
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_BY_CODE_ENABLED = False
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        },
    },
    'microsoft': {
        'SCOPE': ['User.Read'],
        'APP': {
            'client_id': os.environ.get('MICROSOFT_CLIENT_ID', ''),
            'secret': os.environ.get('MICROSOFT_CLIENT_SECRET', ''),
        },
    },
}

# ============================================================
# EMAIL — configure SMTP for newsletter and contact form emails
# In development, emails are printed to the console.
# In production, set EMAIL_* env vars to use real SMTP.
# ============================================================
_EMAIL_HOST = os.environ.get('EMAIL_HOST', '')

if _EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = _EMAIL_HOST
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    # Development: print emails to console instead of sending
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@uscontenthub.com'

CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'tusharlimbasiya200@gmail.com')

# ============================================================
# LOGGING — track errors and slow queries in production
# ============================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}
