"""
Django settings for writeflow project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import urllib.parse as _urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-in-production')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1')

# Build ALLOWED_HOSTS: explicit env var + auto-detect Vercel domain
_allowed = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
_vercel_url = os.environ.get('VERCEL_URL', '')          # e.g. us-content-hub.vercel.app
_vercel_branch_url = os.environ.get('VERCEL_BRANCH_URL', '')
for _vh in [_vercel_url, _vercel_branch_url]:
    if _vh and _vh not in _allowed:
        _allowed.append(_vh)
ALLOWED_HOSTS = _allowed

# Build CSRF origins: explicit env var + auto-detect Vercel URL
_csrf = [o.strip() for o in os.environ.get('DJANGO_CSRF_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',') if o.strip()]
if _vercel_url and f'https://{_vercel_url}' not in _csrf:
    _csrf.append(f'https://{_vercel_url}')
CSRF_TRUSTED_ORIGINS = _csrf

# ── Guard: fail loudly if insecure default key is used in production ──
if not DEBUG and SECRET_KEY == 'django-insecure-dev-only-change-in-production':
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable must be set to a strong random "
        "value in production. Never use the insecure development default."
    )

# Site URL — used in robots.txt, sitemaps, and email links
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000').rstrip('/')

# Google AdSense publisher ID — used in ads.txt
ADSENSE_PUBLISHER_ID = os.environ.get('ADSENSE_PUBLISHER_ID', 'pub-2673860903932624')

# IndexNow key — instantly notifies Bing/Yandex/etc. when articles publish.
# The key is served at /<key>.txt and sent with each submission ping.
INDEXNOW_KEY = os.environ.get('INDEXNOW_KEY', 'a3f1c9e84b7d4e2fa6c0b51d9e8273f4')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django.contrib.postgres',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'blog',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves static files in production
    'django.middleware.gzip.GZipMiddleware',
    'writeflow.middleware.SecurityHeadersMiddleware',  # adds Permissions-Policy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'writeflow.urls'

_TEMPLATE_LOADERS = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'blog' / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            # In production, wrap loaders in cached.Loader so templates are
            # parsed once and reused — eliminates repeated disk I/O per request.
            'loaders': (
                _TEMPLATE_LOADERS
                if DEBUG
                else [('django.template.loaders.cached.Loader', _TEMPLATE_LOADERS)]
            ),
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.publications',
            ],
        },
    },
]

WSGI_APPLICATION = 'writeflow.wsgi.application'


# ============================================================
# DATABASE — PostgreSQL only
# Set DATABASE_URL env var:
#   postgres://user:pass@host:5432/dbname
#   postgresql://user:pass@host:5432/dbname
# Local dev: set DATABASE_URL in your .env file.
# ============================================================
_DATABASE_URL = os.environ.get('DATABASE_URL', '')

if not _DATABASE_URL or not _DATABASE_URL.startswith(('postgres://', 'postgresql://')):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "DATABASE_URL environment variable is required and must be a PostgreSQL URL "
        "(postgres://user:pass@host:5432/dbname). "
        "Set it in your .env file for local development or in your hosting environment for production."
    )

_parsed = _urlparse.urlparse(_DATABASE_URL)
_qs = dict(_urlparse.parse_qsl(_parsed.query))
_pg_options = {
    'sslmode': _qs.get('sslmode', 'require'),
    'connect_timeout': int(_qs.get('connect_timeout', '10')),
}
if 'channel_binding' in _qs:
    _pg_options['channel_binding'] = _qs['channel_binding']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _parsed.path.lstrip('/'),
        'USER': _parsed.username or '',
        'PASSWORD': _parsed.password or '',
        'HOST': _parsed.hostname or 'localhost',
        'PORT': _parsed.port or 5432,
        'CONN_MAX_AGE': 0,
        'OPTIONS': _pg_options,
        'TEST': {
            'NAME': os.environ.get('DATABASE_TEST_NAME', f"test_{_parsed.path.lstrip('/')}")
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django 4.2+ uses STORAGES dict; STATICFILES_STORAGE is removed in Django 6.x.
# whitenoise.storage.CompressedManifestStaticFilesStorage adds content hashes
# to filenames so files can be cached indefinitely — browsers fetch a new URL
# on any change, and whitenoise serves pre-compressed .gz / .br variants.
# Manifest storage requires `collectstatic` to have run, so tests fall back
# to the plain staticfiles backend (no manifest lookup).
_TESTING = 'test' in sys.argv
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if _TESTING
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}
WHITENOISE_MAX_AGE = 31536000  # 1 year

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/accounts/logout/'

# Keep abusive requests from consuming memory on serverless workers.
DATA_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# ============================================================
# CACHING — Redis in production (set REDIS_URL), LocMemCache for dev/tests
# Example: REDIS_URL=redis://localhost:6379/0
# Note: LocMemCache is process-local; on multi-worker deployments each
# worker has its own cache. Switch to Redis for consistency.
# ============================================================
_REDIS_URL = os.environ.get('REDIS_URL', '')

if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
            'TIMEOUT': 300,
        }
    }
else:
    # Development / test fallback — in-process memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'uch-cache-v1',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            },
        }
    }

# ============================================================
# SESSIONS — signed cookies work on Vercel serverless without
# any external storage. Use cache-backed sessions when Redis
# is available (multi-worker / stateful deployments).
# ============================================================
if _REDIS_URL:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
else:
    # signed_cookies: session data lives in the browser cookie,
    # signed + encrypted with SECRET_KEY — no server-side storage needed.
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# ============================================================
# SECURITY SETTINGS — enforced in production
# ============================================================
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    # On by default (Vercel terminates TLS and is HTTPS-only; SECURE_PROXY_SSL_HEADER
    # below tells Django the request was already secure, so no redirect loop).
    # Set DJANGO_SECURE_SSL=false to opt out (e.g. behind a non-TLS internal proxy).
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL', 'true').lower() in ('true', '1')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ============================================================
# ALLAUTH — Social Authentication (Google, Microsoft)
# ============================================================
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_BY_CODE_ENABLED = False
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        },
    },
    'microsoft': {
        'SCOPE': ['User.Read'],
        'APP': {
            'client_id': os.environ.get('MICROSOFT_CLIENT_ID', ''),
            'secret': os.environ.get('MICROSOFT_CLIENT_SECRET', ''),
        },
    },
}

# ============================================================
# EMAIL — configure SMTP for newsletter and contact form emails
# In development, emails are printed to the console.
# In production, set EMAIL_* env vars to use real SMTP.
# ============================================================
_EMAIL_HOST = os.environ.get('EMAIL_HOST', '')

if _EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = _EMAIL_HOST
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    # DEFAULT_FROM_EMAIL must be either a bare address or RFC 5322 format:
    #   "Display Name <user@example.com>"
    # If the env var is set but has no '@', assume it's just a display name
    # and auto-wrap it: "Display Name <EMAIL_HOST_USER>"
    _raw_from = os.environ.get('DEFAULT_FROM_EMAIL', '').strip()
    if _raw_from and '@' not in _raw_from:
        DEFAULT_FROM_EMAIL = f'{_raw_from} <{EMAIL_HOST_USER}>'
    else:
        DEFAULT_FROM_EMAIL = _raw_from or EMAIL_HOST_USER
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    # Development: print emails to console instead of sending
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@uscontenthub.com'

CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'tusharlimbasiya200@gmail.com')

# ============================================================
# LOGGING — track errors and slow queries in production
# ============================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}
